spring:
  #配置数据库
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo1
    username: postgres
    password: xiaoyi_wyx
  profiles:
    active: dev
  #配置Jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #配置Redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days
